# Generated by Django 4.0.6 on 2022-07-08 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_actor_firstname_alter_actor_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2, validators=[django.core.validators.MinValueValidator(limit_value=0.0), django.core.validators.MaxValueValidator(limit_value=10.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='firstname',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Please use only letters A-Z', regex='[a-zA-Z]+')]),
        ),
        migrations.AlterField(
            model_name='actor',
            name='lastname',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Please use only letters A-Z', regex='[a-zA-Z]+')]),
        ),
        migrations.AlterField(
            model_name='character',
            name='firstname',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Please use only letters A-Z', regex='[a-zA-Z]+')]),
        ),
        migrations.AlterField(
            model_name='character',
            name='lastname',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Please use only letters A-Z', regex='[a-zA-Z]+')]),
        ),
        migrations.AlterField(
            model_name='director',
            name='firstname',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Please use only letters A-Z', regex='[a-zA-Z]+')]),
        ),
        migrations.AlterField(
            model_name='director',
            name='lastname',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Please use only letters A-Z', regex='[a-zA-Z]+')]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Please use only letters A-Z', regex='[a-zA-Z]+')]),
        ),
    ]
