# Generated by Django 4.0.6 on 2022-07-08 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Please use only letters A-Z, numbers and special characters', regex="[a-zA-Z0-9- '`(){}[]&]+")]),
        ),
    ]
