# Generated by Django 4.0.6 on 2022-07-08 09:00

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2022, 7, 8))]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2022, 7, 8))]),
        ),
    ]
