# Generated by Django 4.0.6 on 2022-07-08 09:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_actor_date_of_birth_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2022, 7, 8))]),
        ),
    ]
