# Generated by Django 4.0.6 on 2022-07-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_director_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='date_of_birth',
        ),
    ]
